/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids.PRJ1_1_2017_19428;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int DROP_TABLE = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int SHOW_TABLES = 12;
  /** RegularExpression Id. */
  int SELECT = 13;
  /** RegularExpression Id. */
  int INSERT_INTO = 14;
  /** RegularExpression Id. */
  int DELETE_FROM = 15;
  /** RegularExpression Id. */
  int NOT_NULL = 16;
  /** RegularExpression Id. */
  int NULL = 17;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 18;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 19;
  /** RegularExpression Id. */
  int REFERENCES = 20;
  /** RegularExpression Id. */
  int VALUES = 21;
  /** RegularExpression Id. */
  int AS = 22;
  /** RegularExpression Id. */
  int FROM = 23;
  /** RegularExpression Id. */
  int WHERE = 24;
  /** RegularExpression Id. */
  int IS = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int ASTERISK = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int LEFT_PAREN = 31;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int PERIOD = 34;
  /** RegularExpression Id. */
  int UNDERSCORE = 35;
  /** RegularExpression Id. */
  int INT_VALUE = 36;
  /** RegularExpression Id. */
  int SIGN = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 39;
  /** RegularExpression Id. */
  int ALPHABET = 40;
  /** RegularExpression Id. */
  int COMP_OP = 41;
  /** RegularExpression Id. */
  int QUOTE = 42;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 43;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 44;
  /** RegularExpression Id. */
  int CHAR_STRING = 45;
  /** RegularExpression Id. */
  int DATE_VALUE = 46;
  /** RegularExpression Id. */
  int NNNN = 47;
  /** RegularExpression Id. */
  int NN = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"drop table\"",
    "\"desc\"",
    "\"show tables\"",
    "\"select\"",
    "\"insert into\"",
    "\"delete from\"",
    "\"not null\"",
    "\"null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"values\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"is\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"*\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "<INT_VALUE>",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<COMP_OP>",
    "\"\\\'\"",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "<NON_QUOTE_CHARACTER>",
    "<CHAR_STRING>",
    "<DATE_VALUE>",
    "<NNNN>",
    "<NN>",
  };

}
